[package]
name = "zunda-tts"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
voicevox-client = { version = "0.1.1", git = "https://github.com/kurotakazuki/voicevox-client.git" }
